### ISSUE TITLE
Exception in thread "main" joptsimple.OptionMissingRequiredArgumentException: Option ['rev'] 

### ISSUE THREAD

**Issue by dwcramer** [linuxserver/docker-mcmyadmin2#1]
Looks like something may have changed upstream in spigot that is affecting this container. 

Docker host: Ubuntu 14.04
Docker version 1.7.1, build 786b29d

```
docker create --name=minecraft -v /appdata/minecraft:/minecraft -e PUID=ubuntu -e PGID=ubuntu -e REV=1.8.7 -p 8080:8080 -p 25565:25565 linuxserver/mcmyadmin:latest
```

Then:

```
docker run linuxserver/mcmyadmin
```

Result:

```
*** Running /etc/my_init.d/30_install_spigotmc.sh...

    **********************************************************
    Building Spigot and craftbukkit this can Take a long time
    **********************************************************
    Go Grab a Coffee/Beer

Loading BuildTools version: git-BuildTools-44af261-40 (#40)
Exception in thread "main" joptsimple.OptionMissingRequiredArgumentException: Option ['rev'] requires an argument
    at joptsimple.RequiredArgumentOptionSpec.detectOptionArgument(RequiredArgumentOptionSpec.java:48)
    at joptsimple.ArgumentAcceptingOptionSpec.handleOption(ArgumentAcceptingOptionSpec.java:256)
    at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:450)
    at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
    at joptsimple.OptionParser.parse(OptionParser.java:379)
    at org.spigotmc.builder.Builder.main(Builder.java:101)
cp: cannot stat ‘/tmp/spigot-.jar’: No such file or directory
cp: cannot stat ‘/tmp/craftbukkit-.jar’: No such file or directory
*** /etc/my_init.d/30_install_spigotmc.sh failed with status 1
```

**Comment by dwcramer** [comment]
Oh, I misunderstood how to run it. This seems to work:

```
docker run --name=minecraft -v /appdata/minecraft:/minecraft -e PUID=ubuntu -e PGID=ubuntu -e REV=1.8.7 -p 8080:8080 -p 25565:25565 linuxserver/mcmyadmin:latest
~~
```

**Comment by lonix** [comment]
Also note that Ubuntu is not a valid pid/gid. If ubuntu is the user you want to emulate you van look up that id by doing -"id -u ubuntu" and "-g-" for Group
